layout: "main"
logger: "console"
appname: "chnforo"
template: "template_toolkit"
log: 'debug'

engines:
        template_toolkit:
            EVAL_PERL: 1
            ENCODING: utf8
            
plugins:
        Database:
            driver: 'mysql'
            database: 'chnforo'
            host: 'localhost'
            username: 'chnuser'
            password: 'maskayerro'
            connectivity-check-threshold: 10
            dbi_params:
                RaiseError: 1
                AutoCommit: 1
            on_connect_do: ["SET NAMES 'utf8'", "SET CHARACTER SET 'utf8'" ]
